Fix ambiguous `widget::operator ==()`
This removes `widget::operator long()`. Due to the conversion operator
as well as the equality operator, MSVC under VS2019 produces the
following error:

```
    xutility(5133,1): error C2666: 'widget::operator ==': 2 overloads have similar conversions
    gcpp\test.cpp(64,2): message : could be 'bool widget::operator ==(const widget &) const'
    xutility(5133,1): message : or       'built-in C++ operator==(long, _Ty)'
```